### ISSUE TITLE
关于A站录制的请教

### ISSUE THREAD

**Issue by vipskycn** [nICEnnnnnnnLee/LiveRecorder#2]
问题1：本想录制A站的直播的，在python方面还是小白所以用了一个小时才成功安装项目，正准备查看配置尝试录制时发现没有A站的配置说明，就是请问下A站的配置是不是跟快手一样。

**Comment by vipskycn** [comment]
仔细看readme发现到版本要求了，眼睛不好使了，也希望作者能回答一下我在python版本的问题啊，先谢了

**Comment by nICEnnnnnnnLee** [comment]
A站录制python版一直处于待施工状态，现在已经完成了。

**Comment by vipskycn** [comment]
感谢大佬！
